// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcznmyitjnwdimmjypki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjem5teWl0am53ZGltbWp5cGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDcxMjEsImV4cCI6MjA2MjIyMzEyMX0.JDeJZVWI33AsTpIKsJuQbC3xUUuq80ECveUyIdv38Q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);